# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Advokatska kancelarija Vukotic & Bujisic
email: office@vukoticbujisic.me
description: > # this means to ignore newlines until "baseurl:"
  Mi smo advokatska kancelarija koja se bavi svim vrstama pravnih poslova i nas moto je zadovoljan korisnik. 
  Advokatsku kancelariju cine dva advokata sa velikim iskustvom u oblastima privrednog, radnog i medjunarodnog prava.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://site.vukoticbujisic.me" # the base hostname & protocol for your site
twitter_username: otvara se
github_username:  rvukotic

# Build settings
markdown: kramdown
